
from src.day_7.problem_1 import Problem1Day7 as Problem


class TestProblem1Day7:
    def test_simple_case(self):
        input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        """

        problem = Problem(input=input)
        answer = problem.answer()

        assert answer == 21
    
    def test_aoc_answer(self):
        problem = Problem()
        answer = problem.answer()

        assert answer == 1550
